### PR TITLE
UniversalRisky GameObject names added to risky check

### PR DESCRIPTION
**Pull request by Psychloor**
Accordingly to [emmVRC Risky Function Requests](https://github.com/emmVRC/emmVRC-Risky-Function-Request) they've chanegd the gameobject names to "UniversalRiskyFuncDisable/Enable" so support for those too got added

### CODE REVIEW

**Review by Psychloor — COMMENTED** [review]
that's all with no more commits

**Review by Psychloor — COMMENTED** [review]
emmvrc and remod does it this way too. supposed to be only root object so

**Comment by Sarayalth** [comment]
looks good to me, but:

> emmvrc and remod does it this way too. supposed to be only root object so

i just tested it in a world that doesnt have the gameobject on the root and emmvrc ended up disabling risky functions, so i guess they are using GameObject.Find() :/

**Comment by Psychloor** [comment]
those things are if the gameobjects exists just like gameobject.find does.

**Comment by Psychloor** [comment]
if the world doesn't ahve either then how'd it supposed to react?

**Comment by Psychloor** [comment]
if emmvrc reacted then the id is blocked

**Comment by Psychloor** [comment]
https://github.com/SleepyVRC/Mods/blob/main/VRChatUtilityKit/Utilities/VRCUtils.cs#L144
if not in the api then check the gameobjects and tags

**Comment by Sarayalth** [comment]
the world i tested this with (`wrld_4321dc41-ea7e-4a24-9236-0bf5015aeb3d`) is not in the api (doesnt return "allowed" or "denied") so it falls back to checking for the game object

in this specific world, the gameobject `eVRCRiskFuncDisable` is not a root object, its a child of `VRCWorld`

image

but emmvrc still detects that the object exists and disables risky functions, probably because they are using `GameObject.Find()` instead of using `SceneManager.GetActiveScene().GetRootGameObjects()` as this pr and remod uses
this means that vrcuk will not detect the gameobject unless its a root object and potentially enabling risky functions in worlds where it wouldnt enable it before

**Comment by Psychloor** [comment]
if this works better? still following guidelines of emmvrc nowadays as mentionied in first comment

**Comment by Sarayalth** [comment]
yeah, this way it follows emmvrc's implementation 👍

**Review by Sarayalth — APPROVED** [review]

**Pull request merged**
